name: Feature request
description: Proposer une nouvelle fonctionnalité
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème à résoudre
      description: Quelle frustration ou besoin cette feature adresse-t-elle ?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Périmètre
      options:
        - Mobile
        - Web
        - Les deux
    validations:
      required: true
