const EMOJI_MAP: Record<string, string> = {
  oignon: "🧅", oignons: "🧅",
  ail: "🧄",
  echalote: "🧅", echalotes: "🧅",
  carotte: "🥕", carottes: "🥕",
  tomate: "🍅", tomates: "🍅",
  courgette: "🥒", courgettes: "🥒",
  poivron: "🫑", poivrons: "🫑",
  epinards: "🥬",
  champignons: "🍄", "champignons de paris": "🍄",
  "pomme de terre": "🥔", "pommes de terre": "🥔",
  "patate douce": "🍠",
  brocoli: "🥦",
  "chou-fleur": "🥦",
  laitue: "🥬", salade: "🥬",
  poireaux: "🌿",
  concombre: "🥒",
  avocat: "🥑",
  aubergine: "🍆", aubergines: "🍆",
  mais: "🌽", "epi de mais": "🌽",
  artichaut: "🌿", artichauts: "🌿",
  asperge: "🌿", asperges: "🌿",
  celeri: "🌿",
  fenouil: "🌿",
  radis: "🌿",
  navet: "🌿", navets: "🌿",
  betterave: "🌿", betteraves: "🌿",
  butternut: "🎃", "courge butternut": "🎃",
  courge: "🎃",
  potiron: "🎃", potimarron: "🎃",
  ciboulette: "🌿",
  pois: "🫛", "petits pois": "🫛",
  haricots: "🫘", "haricots verts": "🫛",
  chou: "🥬", "chou rouge": "🥬", "chou vert": "🥬",
  citron: "🍋", "citron vert": "🍋",
  orange: "🍊",
  pomme: "🍎", pommes: "🍎",
  banane: "🍌",
  fraise: "🍓", fraises: "🍓",
  cerise: "🍒", cerises: "🍒",
  raisin: "🍇",
  peche: "🍑", peches: "🍑",
  poire: "🍐", poires: "🍐",
  mangue: "🥭", mangues: "🥭",
  ananas: "🍍",
  melon: "🍈",
  pasteque: "🍉",
  kiwi: "🥝", kiwis: "🥝",
  myrtille: "🫐", myrtilles: "🫐",
  framboise: "🍓", framboises: "🍓",
  poulet: "🍗", "poulet entier": "🍗", "blanc de poulet": "🍗", "blancs de poulet": "🍗",
  boeuf: "🥩", "boeuf hache": "🥩", steak: "🥩",
  saumon: "🐟", "saumon frais": "🐟", "saumon fume": "🐟",
  thon: "🐟", "thon en boite": "🐟",
  lardons: "🥓",
  jambon: "🥩",
  oeuf: "🥚", oeufs: "🥚",
  "jaune d oeuf": "🥚", "jaunes d oeuf": "🥚",
  "blanc d oeuf": "🥚", "blancs d oeuf": "🥚",
  crevettes: "🍤",
  moules: "🦪",
  cabillaud: "🐟", "filet de cabillaud": "🐟",
  sole: "🐟",
  sardine: "🐟", sardines: "🐟",
  porc: "🥩", "cote de porc": "🥩", "filet de porc": "🥩",
  agneau: "🥩", "gigot d agneau": "🥩",
  dinde: "🍗", "blanc de dinde": "🍗",
  canard: "🍗", "magret de canard": "🍗",
  chorizo: "🌶️",
  merguez: "🌭",
  saucisse: "🌭", saucisses: "🌭",
  lait: "🥛", "lait demi-ecreme": "🥛", "lait entier": "🥛",
  "lait de coco": "🥥",
  beurre: "🧈",
  "creme fraiche": "🥛", "creme liquide": "🥛",
  parmesan: "🧀", mozzarella: "🧀",
  gruyere: "🧀", "gruyere rape": "🧀",
  emmental: "🧀", "emmental rape": "🧀",
  reblochon: "🧀", comte: "🧀", roquefort: "🧀",
  camembert: "🧀", brie: "🧀", chevre: "🧀",
  cheddar: "🧀", ricotta: "🧀", mascarpone: "🧀",
  fromage: "🧀", "fromage rape": "🧀",
  yaourt: "🥛",
  farine: "🌾", "farine t55": "🌾", "farine de ble": "🌾",
  riz: "🍚", "riz basmati": "🍚",
  pates: "🍝", spaghetti: "🍝", penne: "🍝", lasagnes: "🍝",
  pain: "🍞",
  lentilles: "🫘", "pois chiches": "🫘",
  maizena: "🌽", "fecule de mais": "🌽",
  chapelure: "🍞",
  sel: "🧂",
  poivre: "🧂",
  sucre: "🍬", "sucre roux": "🍬", "sucre brun": "🍬",
  miel: "🍯",
  huile: "🫙", "huile d olive": "🫒", "huile de tournesol": "🫙", "huile de sesame": "🫙",
  vinaigre: "🫙", "vinaigre balsamique": "🫙",
  moutarde: "🫙",
  "sauce soja": "🫙",
  persil: "🌿", basilic: "🌿", coriandre: "🌿", menthe: "🌿",
  thym: "🌿", laurier: "🌿", "herbes de provence": "🌿",
  cumin: "🫙", paprika: "🫙", curcuma: "🫙", cannelle: "🫙",
  curry: "🫙", "tikka masala": "🫙", gingembre: "🫙", "gingembre en poudre": "🫙",
  "noix de muscade": "🌰", muscade: "🌰",
  vin: "🍷", "vin rouge": "🍷", "vin blanc": "🥂", "vin rose": "🍷",
  cidre: "🍺", biere: "🍺",
  chocolat: "🍫", "chocolat noir": "🍫", cacao: "🍫",
  vanille: "🌿",
  levure: "🫙", "levure chimique": "🫙", "levure de boulanger": "🫙",
  bicarbonate: "🫙",
  "bouillon cube": "🍲",
  "bouillon de legumes": "🍲", "bouillon de poulet": "🍲", "bouillon de boeuf": "🍲",
  "tomates concassees": "🍅", "tomates en boite": "🍅",
  "concentre de tomates": "🍅", "sauce tomate": "🍅",
  "creme de coco": "🥥",
  "pate feuilletee": "🥐", "pate brisee": "🥐", "pate sablee": "🥐",
  "pate a pizza": "🍕",
  "pate a crepes": "🥞",
  tahini: "🫙",
  confiture: "🍯",
};

function normalize(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/['''`]/g, " ")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

export function getIngredientEmoji(name: string): string | null {
  const key = normalize(name);
  if (EMOJI_MAP[key]) return EMOJI_MAP[key];
  for (const [k, v] of Object.entries(EMOJI_MAP)) {
    if (key.startsWith(k) || k.startsWith(key)) return v;
  }
  return null;
}
